apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: nginx
spec:
  clusterIP: None  # Headless service
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "web"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          projected:
            sources:
              - downwardAPI:
                  items:
                    - path: index.html
                      fieldRef:
                        fieldPath: metadata.name